#!/usr/bin/env python3
"""Generate per-state tray icon variants from the 'HR' circle base.

The base icon is generated by ``make-text-icon.py``; this script adds the
status-dot overlay (green/yellow/grey/red) for each state.

Outputs: ``~/.local/share/icons/hicolor/256x256/apps/hermes-router-{state}-{size}.png``
"""
from __future__ import annotations

import os
import subprocess
from pathlib import Path

from PIL import Image, ImageDraw

OUT_DIR = Path(
    os.environ.get(
        "HERMES_ROUTER_ICON_DIR",
        str(Path("~/.local/share/icons/hicolor/256x256/apps").expanduser()),
    )
)
OUT_DIR.mkdir(parents=True, exist_ok=True)

DOT_COLORS = {
    "running": (60, 162, 60, 255),  # green
    "starting": (220, 180, 40, 255),  # yellow
    "stopped": (140, 140, 140, 255),  # grey
    "error": (200, 50, 50, 255),  # red
}

SIZES = [32, 48, 64, 96, 128, 256]
STATES = ["running", "starting", "stopped", "error"]


def render(base: Image.Image, state: str, size: int) -> Image.Image:
    """Build a ``size``-pixel state icon with a status-dot overlay."""
    out = base.resize((size, size), Image.LANCZOS)
    color = DOT_COLORS[state]
    dot_r = max(6, size // 8)
    halo_r = dot_r + max(1, size // 32)
    cx = cy = size - dot_r - 1
    draw = ImageDraw.Draw(out)
    draw.ellipse(
        (cx - halo_r, cy - halo_r, cx + halo_r, cy + halo_r),
        fill=(255, 255, 255, 255),
    )
    draw.ellipse(
        (cx - dot_r, cy - dot_r, cx + dot_r, cy + dot_r), fill=color
    )
    return out


def ensure_base_icon() -> Image.Image:
    """Run ``make-text-icon.py`` if the base icon is missing."""
    base_path = OUT_DIR / "hermes-router-circle-256.png"
    if not base_path.exists():
        script = Path(__file__).resolve().parent / "make-text-icon.py"
        if script.exists():
            subprocess.run([str(script)], check=True)
    if not base_path.exists():
        msg = f"base icon not found at {base_path}; run scripts/make-text-icon.py"
        raise FileNotFoundError(msg)
    return Image.open(base_path).convert("RGBA")


def main() -> int:
    base = ensure_base_icon()
    for state in STATES:
        for size in SIZES:
            out = OUT_DIR / f"hermes-router-{state}-{size}.png"
            render(base, state, size).save(out, "PNG")
            print(f"wrote {out}")
        # canonical 64px
        canon = OUT_DIR / f"hermes-router-{state}.png"
        render(base, state, 64).save(canon, "PNG")
        print(f"wrote {canon}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
